name: 'Triaging'
description: "GitHub action analysing new issue body for adding labels and comment."
author: "Arhia"
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  config-path:
    description: 'Path to the config file'
    default: '.github/triage_bot_config.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
