name: 'Test triaging'
on:
  pull_request:
    branches:
    - test
jobs:
  triaging:
    runs-on: ubuntu-latest
    name: Check bundle size
    steps:
    - uses: actions/checkout@v2
    - name: Create comment
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        build-script: "build"
        pattern: "./dist/"